# Generated by Django 5.2.1 on 2025-05-27 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.itemmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cartItems',
            },
        ),
        migrations.CreateModel(
            name='CartServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateVisit', models.DateTimeField()),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.servicemodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cartServices',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возврат')], default='pending', max_length=20)),
                ('paymentMethod', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('other', 'Другое')], max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('transactionId', models.CharField(blank=True, max_length=100, null=True)),
                ('itemsId', models.ManyToManyField(blank=True, related_name='payments', to='Carts.cartitemmodel')),
                ('servicesId', models.ManyToManyField(blank=True, related_name='payments', to='Carts.cartservicemodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-createdAt'],
            },
        ),
    ]
