# Generated by Django 5.2.1 on 2025-05-27 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True)),
                ('typeResource', models.IntegerField(choices=[(1, 'for ItemModel'), (2, 'for ServiceModel')], default=1)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('typeId', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Services.typemodel')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('typeId', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Services.typemodel')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
