# Generated by Django 5.2.1 on 2025-05-27 15:42

import Services.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(blank=True, default='default/s1.png', storage=Services.models.OverwriteStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='typeId',
            field=models.ForeignKey(limit_choices_to={'typeResource': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Services.typemodel'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='typeId',
            field=models.ForeignKey(limit_choices_to={'typeResource': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Services.typemodel'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='iconId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Services.iconmodel'),
        ),
    ]
